import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import AnimatedCursor from "react-animated-cursor";
const clashDisplay = localFont({
  src: "../../public/ClashDisplay-Regular.otf",
  variable: "--font-clash",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <AnimatedCursor
          innerSize={18}
          outerSize={18}
          color="255,255,255"
          // color="230, 112, 17"
          outerAlpha={0.4}
          innerScale={1.4}
          outerScale={10}
          clickables={[
            "a",
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            "label[for]",
            "select",
            "textarea",
            "button",
            ".link",
          ]}
        />
        <body
          className={`${clashDisplay.variable} ${geistMono.variable} antialiased font-sans`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
