import React from "react";
import "./TheyTrustedUs.css";
import betterscanLogo from "../../assets/betterscanlogotext.svg";
function TheyTrustedUs() {
  return (
    <div className="they-trusted-us-container">
      <div className="they-trusted-us-logo-container">
        <img
          id="betterscan-logo"
          src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fbetterscanlogotext.svg?alt=media&token=e719a4f5-1a3e-4975-b7ff-ac35d75a4a56"
          alt="BetterScan"
        />
        <div>
          <img
            id="mywatcher-logo"
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fmywatcher.png?alt=media&token=e13ff983-2def-4e6c-ab8d-cf0aa894ddfc"
            alt=""
          />
        </div>
        <div>
          <img
            id="sofan-logo"
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fsofan.svg?alt=media&token=bd2ffac3-8c87-4735-b69f-7c71e5254cc2"
            alt=""
          />
        </div>
        <div>
          <img
            id="lux-logo"
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Flogo-lux-icon.png?alt=media&token=99e1de68-baf1-40f1-a79a-4ed04f8697d0"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2FMetalyde.jpg?alt=media&token=410f1627-42a2-48e1-99b9-6cce84a69875"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2FGlobal%20expertise.jpg?alt=media&token=9c979a72-1ef8-4695-a94f-7ad915f752c3"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Frepublike.png?alt=media&token=4fc66cb8-ddef-46b0-bdd8-562650947907"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fharbor.jpg?alt=media&token=7024c11c-cdee-491d-965c-fd84c68644d2"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fla-capsule.svg?alt=media&token=f494bdfe-cb63-4004-aaec-79e9e8fdd926"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fhtml_agency.svg?alt=media&token=93ed4b1c-6381-4a7a-b576-274cb785aba8"
            alt=""
          />
        </div>
        {/* Duplication du contenu pour le défilement continu */}
        <img
          src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fbetterscanlogotext.svg?alt=media&token=e719a4f5-1a3e-4975-b7ff-ac35d75a4a56"
          alt="BetterScan"
        />
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fmywatcher.png?alt=media&token=e13ff983-2def-4e6c-ab8d-cf0aa894ddfc"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fsofan.svg?alt=media&token=bd2ffac3-8c87-4735-b69f-7c71e5254cc2"
            alt=""
          />
        </div>
        <div>
          <img
            id="lux-logo"
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Flogo-lux-icon.png?alt=media&token=99e1de68-baf1-40f1-a79a-4ed04f8697d0"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2FMetalyde.jpg?alt=media&token=410f1627-42a2-48e1-99b9-6cce84a69875"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2FGlobal%20expertise.jpg?alt=media&token=9c979a72-1ef8-4695-a94f-7ad915f752c3"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Frepublike.png?alt=media&token=4fc66cb8-ddef-46b0-bdd8-562650947907"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fharbor.jpg?alt=media&token=7024c11c-cdee-491d-965c-fd84c68644d2"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fla-capsule.svg?alt=media&token=f494bdfe-cb63-4004-aaec-79e9e8fdd926"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://firebasestorage.googleapis.com/v0/b/jw-corp.appspot.com/o/partners-logo%2Fhtml_agency.svg?alt=media&token=93ed4b1c-6381-4a7a-b576-274cb785aba8"
            alt=""
          />
        </div>
      </div>
    </div>
  );
}

export default TheyTrustedUs;
